# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[['France' nan 72000.0]
 ['Spain' 42.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 74000.0]
 ['France' 35.0 58000.0]
 ['Spain' 34.0 52000.0]
 ['France' 48.0 nan]
 ['Germany' 27.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes']


## Taking care of missing data

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [6]:
print(X)

[['France' 36.77777777777778 72000.0]
 ['Spain' 42.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 74000.0]
 ['France' 35.0 58000.0]
 ['Spain' 34.0 52000.0]
 ['France' 48.0 63222.22222222222]
 ['Germany' 27.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 36.77777777777778 72000.0]
 [0.0 0.0 1.0 42.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 74000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 34.0 52000.0]
 [1.0 0.0 0.0 48.0 63222.22222222222]
 [0.0 1.0 0.0 27.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 0 0 1]


## Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [12]:
print(X_train)

[[0.0 0.0 1.0 34.0 52000.0]
 [0.0 1.0 0.0 40.0 74000.0]
 [1.0 0.0 0.0 36.77777777777778 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 42.0 48000.0]
 [1.0 0.0 0.0 48.0 63222.22222222222]
 [0.0 1.0 0.0 27.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [14]:
print(y_train)

[0 1 0 0 1 0 0 1]


In [15]:
print(y_test)

[0 1]


## Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
print(X_train)

[[-0.77459667 -0.57735027  1.29099445 -0.62360776 -1.08065978]
 [-0.77459667  1.73205081 -0.77459667  0.41654109  0.91673239]
 [ 1.29099445 -0.57735027 -0.77459667 -0.14205737  0.73515129]
 [-0.77459667 -0.57735027  1.29099445  0.06982481 -0.2635448 ]
 [-0.77459667 -0.57735027  1.29099445  0.76325737 -1.44382199]
 [ 1.29099445 -0.57735027 -0.77459667  1.80340622 -0.06178802]
 [-0.77459667  1.73205081 -0.77459667 -1.83711474  1.73384737]
 [ 1.29099445 -0.57735027 -0.77459667 -0.45024962 -0.53591646]]


In [18]:
print(X_test)

[[-0.77459667  1.73205081 -0.77459667 -1.31704032 -0.89907867]
 [ 1.29099445 -0.57735027 -0.77459667 -0.10353333  0.28119852]]
